### ISSUE TITLE
sync ionic version

### ISSUE THREAD

**Issue by atefBB** [robingenz/docker-ionic-capacitor#10]
Hi, in the docker file this line `ARG IONIC_VERSION=7.2.0` specify a version (this [line](https://github.com/robingenz/docker-ionic-capacitor/blob/8aebc84af3fd380fa642973cbdf7adedd36e3c9b/Dockerfile#L16)) but in readme file u said ionic version is 6 !

**Comment by robingenz** [comment]
Thank you! Done, see https://github.com/robingenz/docker-ionic-capacitor/commit/48425d2f08ed22e19892cb61370736c6447226cb
