### ISSUE TITLE
ERR_UNSUPPORTED_API_LEVEL: Unsupported API level: 34

### ISSUE THREAD

**Issue by LeeSkies** [robingenz/docker-ionic-capacitor#12]
Hi!

I was so happy to stumble upon this repo, been having <title> issue for decades, but when trying to run `npx cap run android` after building with `yarn build` I'm still getting this issue :/

So i'm thinking maybe the problem is with the project's config itself? I'm leaving this here anyway just in case.

Thanks for any help in advance.

**Comment by robingenz** [comment]
This docker image is for building the app, not for running it.
