### ISSUE TITLE
Gradle download `downloads.gradle-dn.com` url changed.

### ISSUE THREAD

**Issue by tbscode** [robingenz/docker-ionic-capacitor#4]
I get a resource not found error when fetching from `https://downloads.gradle-dn.com/distributions/gradle-${GRADLE_VERSION}-bin.zip`.

I've checked the current gradle download url and it seems using `https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip` solves my issue.

so updating the `Dockerfile`:

```dockerfile
RUN mkdir $GRADLE_HOME \
    && curl -sL https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o gradle-${GRADLE_VERSION}-bin.zip \
    && unzip -d $GRADLE_HOME gradle-${GRADLE_VERSION}-bin.zip
```

**Comment by robingenz** [comment]
Thank you!
